[de]
  languageName = "Deutsch"
  title = "Wochennotiz"
  weight = 2
  contentDir = "content/de"
  fallback = "en"

[en]
  languageName = "English"
  title = "weeklyOSM"
  weight = 1
  contentDir = "content/en"

[es]
  languageName = "Español"
  title = "semanarioOSM"
  weight = 3
  contentDir = "content/es"
  fallback = "en"

[fr]
  languageName = "Français"
  title = "hebdoOSM"
  weight = 4
  contentDir = "content/fr"
  fallback = "en"

[it]
  languageName = "Italiano"
  title = "Notiziario Settimanale OSM"
  weight = 5
  contentDir = "content/it"
  fallback = "en"

[pt]
  languageName = "Português"
  weight = 6
  title = "semanárioOSM"
  contentDir = "content/pt"
  fallback = "en"

[pt-br]
  languageName = "Português do Brasil"
  title = "semanárioOSM"
  weight = 7
  contentDir = "content/br"
  fallback = "pt"

[cs]
  languageName = "Čeština"
  title = "týdeník"
  weight = 8
  contentDir = "content/cz"
  fallback = "en"

[ru]
  languageName = "Русский"
  title = "Еженедельник OSM"
  weight = 9
  contentDir = "content/ru"
  fallback = "en"

[uk]
  languageName = "Українська"
  title = "Тижневик OSM"
  weight = 10
  contentDir = "content/uk"
  fallback = "en"

[zh-tw]
  languageName = "台灣中文"
  title = "週刊OSM"
  weight = 11
  contentDir = "content/zh"
  fallback = "en"

[ja]
  languageName = "日本語"
  title = "週刊OSM"
  weight = 12
  contentDir = "content/jp"
  fallback = "en"

[ko]
  languageName = "한국어"
  title = "주간 OSM"
  weight = 13
  contentDir = "content/ko"
  fallback = "en"
