[de]
  languageCode = "de"
  languageName = "Deutsch"
  title = "Wochennotiz"
  weight = 2
  contentDir = "content/de"

[en]
  languageCode = "en"
  languageName = "English"
  title = "weeklyOSM"
  weight = 1
  contentDir = "content/en"

[es]
  languageCode = "es"
  languageName = "Español"
  title = "semanarioOSM"
  weight = 3
  contentDir = "content/es"

[fr]
  languageCode = "fr"
  languageName = "Français"
  title = "hebdoOSM"
  weight = 4
  contentDir = "content/fr"

[it]
  languageCode = "it"
  languageName = "Italiano"
  title = "Notiziario Settimanale OSM"
  weight = 5
  contentDir = "content/it"

[pt]
  languageCode = "pt"
  languageName = "Português"
  weight = 6
  title = "semanárioOSM"
  contentDir = "content/pt"
  fallback = "br"

[br]
  languageCode = "pt-br"
  languageName = "Português do Brasil"
  title = "semanárioOSM"
  weight = 7
  contentDir = "content/br"
  fallback = "pt"

[cz]
  languageCode = "cs"
  languageName = "Čeština"
  title = "týdeník"
  weight = 8
  contentDir = "content/cz"

[ru]
  languageCode = "ru"
  languageName = "Русский"
  title = "Еженедельник OSM"
  weight = 9
  contentDir = "content/ru"

[uk]
  languageCode = "uk"
  languageName = "Українська"
  title = "Тижневик OSM"
  weight = 10
  contentDir = "content/uk"

[zh]
  languageCode = "zh-tw"
  languageName = "台灣中文"
  title = "週刊OSM"
  weight = 11
  contentDir = "content/zh"

[jp]
  languageCode = "ja"
  languageName = "日本語"
  title = "週刊OSM"
  weight = 12
  contentDir = "content/jp"

[ko]
  languageCode = "ko"
  languageName = "한국어"
  title = "주간 OSM"
  weight = 13
  contentDir = "content/ko"