baseURL = 'https://example.org/'
title = 'weeklyOSM'
theme = 'clarity'
languageCode = "en"
defaultContentLanguage = "en"

mainSections = ["blog"]

[languages]
  [languages.de]
    weight = 1
    contentDir = "content/de"
    fallback = "en"
  [languages.en]
    weight = 2
    contentDir = "content/en"

[params]
  rss = true
