baseURL = 'https://weeklyosm.eu/'
title = 'weeklyOSM'
theme = 'clarity'
languageCode = "en"
defaultContentLanguage = "en"


[params]
author = 'weeklyteam'
enableSearch = true
mainSections = ["blog"]
pinFeatured = true
rss = true
