baseURL = 'https://weeklyosm.eu/'
title = 'weeklyOSM'
theme = 'clarity'
languageCode = "en"
defaultContentLanguage = "en"

mainSections = ["blog"]

[params]
  logo = "images/weeklyOSM_logo.png"
  rss = true
