name: Build, Test, and Deploy via SFTP

on: [push, pull_request]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyTest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Build Hugo
        run: hugo --gc --minify

      - name: Build Pagefind
        run: npx pagefind --site public

      - name: Run Integration Tests
        run: pytest tests/test_integration.py -v

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: public/
          retention-days: 1

  deploy:
    needs: build-and-check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: public/

#      - name: Deploy to Server via SFTP (if pushed to main branch)
#          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
#          with:
#            username: ${{ secrets.SFTP_USERNAME }}
#            server: ${{ secrets.SFTP_SERVER }}
#            ssh_private_key: ${{ secrets.SFTP_SSH_KEY }}
#            local_path: './public/*'
#            remote_path: '/var/www/my-website'
#            args: '-o ConnectTimeout=5'
